SELECT DISTINCT(COUNT(MINER)) CNT, MINER
FROM `bigquery-public-data.crypto_ethereum.blocks`
WHERE TIMESTAMP_TRUNC(timestamp, DAY) BETWEEN TIMESTAMP ("2024-01-01") AND TIMESTAMP ("2024-01-31")
GROUP BY MINER
ORDER BY CNT DESC LIMIT 1000;

SELECT COUNT(DISTINCT(MINER)) CNT
FROM `bigquery-public-data.crypto_ethereum.blocks`
WHERE TIMESTAMP_TRUNC(timestamp, DAY) BETWEEN TIMESTAMP ("2024-01-01") AND TIMESTAMP ("2024-01-31") LIMIT 1000;

SELECT COUNT(MINER)
FROM `bigquery-public-data.crypto_ethereum.blocks`
WHERE TIMESTAMP_TRUNC(timestamp, DAY) BETWEEN TIMESTAMP ("2024-01-01") AND TIMESTAMP ("2024-01-31") LIMIT 1000;
